name: Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [ x86, x64 ]
    steps:    
    - uses: microsoft/setup-msbuild@v1

    - uses: abel0b/setup-premake@v2
      with:
        version: "5.0.0-beta1"

    - uses: nuget/setup-nuget@v1

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build SUWSF
      run: |
        nuget restore SUWSF.sln
        msbuild SUWSF.sln -p:Configuration=Release -p:Platform=${{ matrix.platform }} -p:BUILDVERSION="${{ github.ref_name }}"
    
    - name: Download Ultimate ASI Loader x64
      if: ${{ matrix.platform == 'x64' }}
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/latest/download/Ultimate-ASI-Loader_x64.zip"
        target: "."

    - name: Download Ultimate ASI Loader x86
      if: ${{ matrix.platform == 'x86' }}
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/latest/download/Ultimate-ASI-Loader.zip"
        target: "."
    
    - name: Prepare for release
      run: |
        7z e Ultimate-ASI-Loader*.zip
        mv *.dll ${{ matrix.platform }}/Release/dsound.dll
        rm ${{ matrix.platform }}/Release/*.pdb
        mv README.md ${{ matrix.platform }}/Release/
        mv LICENSE ${{ matrix.platform }}/Release/
        mv SUWSF.ini ${{ matrix.platform }}/Release/
        7z a -tzip "SUWSF-${{ matrix.platform }}.zip" "./${{ matrix.platform }}/Release/*"
        
    - run: mkdir -p artifact
    
    - uses: actions/upload-artifact@master
      with:
        name: "SUWSF-${{ matrix.platform }}.zip"
        path: artifact

  release:  
    runs-on: windows-2022
    steps:   
    
    - uses: actions/download-artifact@master
      with:
        name: "SUWSF-SUWSF-x64.zip"
        path: artifact
    
    - uses: actions/download-artifact@master
      with:
        name: "SUWSF-SUWSF-x86.zip"
        path: artifact
          
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "SUWSF-SUWSF-x64.zip,SUWSF-SUWSF-x86.zip"
        name: build${{ github.run_number }}
        tag: build${{ github.run_number }}
        prerelease: true
        body: "This is a pre-release version of the Ion Fury Voxel Pack that includes all the latest additions and changes" 